version: "3.0"
services:
  ruby-2-6: &latest
    volumes:
      - project:/app
  ruby-2-5:
    <<: *latest
  ruby-2-4:
    <<: *latest
  ruby-2-3:
    <<: *latest
  ruby-2-2:
    <<: *latest
volumes:
  project:
    external: true
